name: Build & Release Tracenium Agent

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Necesario para electron-builder
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      # Mac necesita tools extra
      - name: Install Mac build deps
        if: matrix.os == 'macos-latest'
        run: brew install rpm

      # Linux necesita tools extra
      - name: Install Linux build deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm fakeroot dpkg

      - name: Build App
        run: npm run build

      # Publicamos a GitHub Releases
      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            dist/*.msi
            dist/*.pkg
            dist/*.deb
            dist/*.rpm
            dist/*latest*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
