name: Build & Release Tracenium Agent

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create .env file
        run: |
          echo "SERVER_BASE_URL=http://192.168.68.104:3000" > .env
          echo "AGENT_ID=auto" >> .env

      # EVITA EPERM Y SIGINT EN WINDOWS Y MACOS
      - name: Clean node_modules on Windows
        if: matrix.os == 'windows-latest'
        run: if (Test-Path node_modules) { Remove-Item -Recurse -Force node_modules }

      - name: Install Dependencies
        run: npm ci

      # Dependencias Linux para crear deb/rpm
      - name: Install Linux build deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm fakeroot dpkg

      # SOLO Linux publica releases
      - name: Build App
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build

      - name: Upload Release Artifacts
        if: matrix.os == 'ubuntu-latest' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            dist/*.msi
            dist/*.pkg
            dist/*.deb
            dist/*.rpm
            dist/*.zip
            dist/*latest*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
